### ISSUE TITLE
Error: Cannot find module 'pdfjs-dist/legacy/build/pdf'

### ISSUE THREAD

**Issue by bloemy7** [opengovsg/pdf2md#85]
**Describe the bug**
Without changing any code, I am now getting this error on build:
`Error: Cannot find module 'pdfjs-dist/legacy/build/pdf' Require stack: - /workspace/node_modules/@opendocsg/pdf2md/lib/util/pdf.js - /workspace/node_modules/@opendocsg/pdf2md/lib/pdf2md.js - /workspace/index.js`

**To Reproduce**
1. Build with latest 0.1.30 version

**Expected behavior**
Able to build

**Comment by LoneRifle** [comment]
Hi, thanks for spotting this. Do you have a GitHub repository that reproduces this?

**Comment by LoneRifle** [comment]
Fixed in 767ffcc
